// START: Login, Logout and Registration

POST https://tictactoe.aboutdream.io/register/
Content-Type: application/json

{
  "username": "domagojsed",
  "password": "mypassword"
}

###

POST https://tictactoe.aboutdream.io/login/
Content-Type: application/json

{
  "username": "domagoj",
  "password": "mypassword"
}

###

POST https://tictactoe.aboutdream.io/logout/
Content-Type: application/json
Authorization: Bearer d12197b94a5d3cead7a16ae1582697e6b4052a87

// END: Login, Logout and Registration

// START: Authenticated endpoints

###
@authToken = "d12197b94a5d3cead7a16ae1582697e6b4052a87"

GET https://tictactoe.aboutdream.io/games/?offset=0&limit=100
Content-Type: application/json
Authorization: Bearer d12197b94a5d3cead7a16ae1582697e6b4052a87

###

GET https://tictactoe.aboutdream.io/users/?limit=100
Content-Type: application/json
Authorization: Bearer d12197b94a5d3cead7a16ae1582697e6b4052a87

// END: Authenticated endpoints
