// START: Login, Logout and Registration

POST https://tictactoe.aboutdream.io/register/
Content-Type: application/json

{
  "username": "domagojsed",
  "password": "mypassword"
}

###

POST https://tictactoe.aboutdream.io/login/
Content-Type: application/json

{
  "username": "domagoj",
  "password": "mypassword"
}

###

POST https://tictactoe.aboutdream.io/logout/
Content-Type: application/json
Authorization: Bearer bef0559d9f05149119ca902f9c47cc0ad7963718

// END: Login, Logout and Registration

// START: Authenticated endpoints

###
@authToken = "bef0559d9f05149119ca902f9c47cc0ad7963718"

GET https://tictactoe.aboutdream.io/games/?offset=10&limit=5
Content-Type: application/json
Authorization: Bearer bef0559d9f05149119ca902f9c47cc0ad7963718

###

GET https://tictactoe.aboutdream.io/users/?limit=10
Content-Type: application/json
Authorization: Bearer bef0559d9f05149119ca902f9c47cc0ad7963718

###

GET https://tictactoe.aboutdream.io/users/359/
Content-Type: application/json
Authorization: Bearer bef0559d9f05149119ca902f9c47cc0ad7963718

// END: Authenticated endpoints
